version: "3.9"

services:

  airport-service:
    container_name: airport-service
    image: airport-service
    environment:
      DB_SERVER: "sql-server"
      SERVICE_NAME: "Airport"
      SERVICE_PORT: "6001"
      RABBITMQ_HOST: "rabbitmq"
      RABBITMQ_PORT: "5672"
    ports:
    - "6001:80"
    build:
      context: ./Services/AirportService
    depends_on:
      - sql-server
      - rabbitmq
      - service-registry

  airplane-service:
    container_name: airplane-service
    image: airplane-service
    environment:
      DB_SERVER: "sql-server"
      SERVICE_NAME: "Airplane"
      SERVICE_PORT: "6002"
      RABBITMQ_HOST: "rabbitmq"
      RABBITMQ_PORT: "5672"
    ports:
    - "6002:80"
    build:
      context: ./Services/AirplaneService
    depends_on:
      - sql-server
      - rabbitmq
      - service-registry

  flight-service:
    container_name: flight-service
    image: flight-service
    environment:
      DB_SERVER: "sql-server"
      SERVICE_NAME: "Flight"
      SERVICE_PORT: "6003"
      RABBITMQ_HOST: "rabbitmq"
      RABBITMQ_PORT: "5672"
    ports:
    - "6003:80"
    build:
      context: ./Services/FlightService
    depends_on:
      - sql-server
      - rabbitmq
      - service-registry

  reservation-service:
    container_name: reservation-service
    image: reservation-service
    environment:
      DB_SERVER: "sql-server"
      SERVICE_NAME: "Reservation"
      SERVICE_PORT: "6004"
      RABBITMQ_HOST: "rabbitmq"
      RABBITMQ_PORT: "5672"
    ports:
    - "6004:80"
    build:
      context: ./Services/ReservationService
    depends_on:
      - sql-server
      - rabbitmq
      - service-registry

  service-registry:
    container_name:  service-registry
    image:  service-registry
    environment:
      DB_SERVER: "sql-server"
      SERVICE_NAME: "ServiceRegistry"
      RABBITMQ_HOST: "rabbitmq"
      RABBITMQ_PORT: "5672"
    ports:
    - "6000:80"
    build:
      context: ./ServiceRegistry
    depends_on:
      - sql-server
      - rabbitmq

  sql-server:
    container_name: sql-server
    image: mcr.microsoft.com/mssql/server:latest
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "yourStrong(!)Password"
      MSSQL_PID: Express
    ports:
      - "1434:1433"

  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:management
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmqdata:/var/lib/rabbitmq
    hostname: rabbitmq

volumes:
  rabbitmqdata: