version: "3.9"

services:
  airport-service:
    container_name: airport-service
    image: airport-service
    environment:
      DB_SERVER: "sql-server"
      SERVICE_NAME: "Airport"
      RABBITMQ_HOST: "rabbitmq"
      RABBITMQ_PORT: "5672"
    ports:
    - "6001:80"
    build:
      context: ./Services/Airport

  plane-service:
    container_name: plane-service
    image: plane-service
    environment:
      DB_SERVER: "sql-server"
      SERVICE_NAME: "Plane"
      RABBITMQ_HOST: "rabbitmq"
      RABBITMQ_PORT: "5672"
    ports:
    - "6002:80"
    build:
      context: ./Services/PlaneTransport

  sql-server:
    container_name: sql-server
    image: mcr.microsoft.com/mssql/server:latest
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "yourStrong(!)Password"
      MSSQL_PID: Express
    ports:
      - "1434:1433"

  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:management
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmqdata:/var/lib/rabbitmq
    hostname: rabbitmq

volumes:
  rabbitmqdata: