// <auto-generated />
using Airport.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Airport.Migrations
{
    [DbContext(typeof(AirportContext))]
    [Migration("20221218204428_StartDatabase")]
    partial class StartDatabase
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.17")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Airport.Models.Airport", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("airport_id")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<long>("AirportAddressId")
                        .HasColumnType("bigint")
                        .HasColumnName("airport_address_id");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("description");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.HasIndex("AirportAddressId")
                        .IsUnique();

                    b.ToTable("airport");
                });

            modelBuilder.Entity("Airport.Models.AirportAddress", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("airport_address_id")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AirportId")
                        .HasColumnType("int")
                        .HasColumnName("airport_id");

                    b.Property<string>("City")
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("city");

                    b.Property<string>("Country")
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("country");

                    b.Property<string>("Zip")
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("zip");

                    b.HasKey("Id");

                    b.HasIndex("City")
                        .IsUnique()
                        .HasFilter("[city] IS NOT NULL");

                    b.HasIndex("Country")
                        .IsUnique()
                        .HasFilter("[country] IS NOT NULL");

                    b.HasIndex("Zip")
                        .IsUnique()
                        .HasFilter("[zip] IS NOT NULL");

                    b.ToTable("airport_address");
                });

            modelBuilder.Entity("Airport.Models.Airport", b =>
                {
                    b.HasOne("Airport.Models.AirportAddress", "AirportAddress")
                        .WithOne("Airport")
                        .HasForeignKey("Airport.Models.Airport", "AirportAddressId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AirportAddress");
                });

            modelBuilder.Entity("Airport.Models.AirportAddress", b =>
                {
                    b.Navigation("Airport");
                });
#pragma warning restore 612, 618
        }
    }
}
