// <auto-generated />
using System;
using FlightService.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace FlightService.Migrations
{
    [DbContext(typeof(FlightContext))]
    [Migration("20221224214818_AirplaneReplications")]
    partial class AirplaneReplications
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.17")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Flight.Models.Flight", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("flight_id")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<long>("AirplaneId")
                        .HasColumnType("bigint")
                        .HasColumnName("airplane_id");

                    b.Property<long>("ArrivalAirportId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("ArrivalTime")
                        .HasColumnType("datetime2")
                        .HasColumnName("arrival_time");

                    b.Property<decimal>("Cost")
                        .HasColumnType("decimal")
                        .HasColumnName("cost");

                    b.Property<long>("DepartureAirportId")
                        .HasColumnType("bigint")
                        .HasColumnName("departure_airport_id");

                    b.Property<DateTime>("DepartureTime")
                        .HasColumnType("datetime2")
                        .HasColumnName("departure_time");

                    b.HasKey("Id");

                    b.HasIndex("ArrivalAirportId");

                    b.HasIndex("DepartureAirportId");

                    b.ToTable("flight");
                });

            modelBuilder.Entity("Flight.Models.Replications.AirplaneSeat", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint")
                        .HasColumnName("airplane_seat_id");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<short>("Line")
                        .HasColumnType("smallint");

                    b.Property<long>("PlaneId")
                        .HasColumnType("bigint");

                    b.Property<short>("Seat")
                        .HasColumnType("smallint");

                    b.HasKey("Id");

                    b.HasIndex("PlaneId");

                    b.ToTable("airplane_seat");
                });

            modelBuilder.Entity("Flight.Models.Replications.Airport", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint")
                        .HasColumnName("airport_id");

                    b.Property<long>("AirportAddressId")
                        .HasColumnType("bigint")
                        .HasColumnName("airport_address_id");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.HasIndex("AirportAddressId")
                        .IsUnique();

                    b.ToTable("airport");
                });

            modelBuilder.Entity("Flight.Models.Replications.AirportAddress", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint")
                        .HasColumnName("airport_address_id");

                    b.Property<int>("AirportId")
                        .HasColumnType("int")
                        .HasColumnName("airport_id");

                    b.Property<string>("City")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("city");

                    b.Property<string>("Country")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("country");

                    b.Property<string>("Zip")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("zip");

                    b.HasKey("Id");

                    b.ToTable("airport_address");
                });

            modelBuilder.Entity("FlightService.Models.Replications.Airplane", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint")
                        .HasColumnName("airplane_id");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("airplane");
                });

            modelBuilder.Entity("Flight.Models.Flight", b =>
                {
                    b.HasOne("Flight.Models.Replications.Airport", "ArrivalAirport")
                        .WithMany("ArrivalFlights")
                        .HasForeignKey("ArrivalAirportId")
                        .HasConstraintName("fk_arrival_airport")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Flight.Models.Replications.Airport", "DepartureAirport")
                        .WithMany("DepartureFlights")
                        .HasForeignKey("DepartureAirportId")
                        .HasConstraintName("fk_departure_airport")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("ArrivalAirport");

                    b.Navigation("DepartureAirport");
                });

            modelBuilder.Entity("Flight.Models.Replications.AirplaneSeat", b =>
                {
                    b.HasOne("FlightService.Models.Replications.Airplane", "Plane")
                        .WithMany("Seats")
                        .HasForeignKey("PlaneId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Plane");
                });

            modelBuilder.Entity("Flight.Models.Replications.Airport", b =>
                {
                    b.HasOne("Flight.Models.Replications.AirportAddress", "AirportAddress")
                        .WithOne("Airport")
                        .HasForeignKey("Flight.Models.Replications.Airport", "AirportAddressId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AirportAddress");
                });

            modelBuilder.Entity("Flight.Models.Replications.Airport", b =>
                {
                    b.Navigation("ArrivalFlights");

                    b.Navigation("DepartureFlights");
                });

            modelBuilder.Entity("Flight.Models.Replications.AirportAddress", b =>
                {
                    b.Navigation("Airport");
                });

            modelBuilder.Entity("FlightService.Models.Replications.Airplane", b =>
                {
                    b.Navigation("Seats");
                });
#pragma warning restore 612, 618
        }
    }
}
